### ISSUE TITLE
User can create a new contact

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/interview-frontend#1]
# Motivation
We want to be able to add a new contact to the list of people.

# Tasks
 - [x] Read Vue Documentation.
- [x] Examine the response object.
- [x] Create a form with basic fields for a Name, email, phone number, and a favorite checkbox.
- [x] Make sure that the name is a required field.
- [x] Be able to submit the form.
- [x] Be able to get a valid response back once you submit the form.
- [x] Be able to verify manually that the entry was added.
- [x] Update the list right after you submit the data without need to refresh.
