### ISSUE TITLE
User can see a formatted list of contacts

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/interview-frontend#3]
# Motivation
We want to be able to see a formatted list of contacts.

# Task
- [x] Read up on SASS integration with vue
- [x] Be able to create a list of alternating colors.
- [x] Be able to style the list as per the requirements.
- [x] Be able to style the items in the list.
- [x] Be able to interact with the items of the list in basic fashion.
