### ISSUE TITLE
User can see contact details when selecting a contact

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/interview-frontend#5]
# Motivation
We want to be able to see the contact information of a selected contact

# Tasks
- [x] Be able to fire an event when an item is selected
- [x] Be able to alert the user of the details of that selected user
- [x] Be able to on a click replace the item with a component if clicked.
- [x] Be able to on a click of the component, turn it back to a simple entry.
- [x] Make sure that the component of the selected contact has the matching information.
- [x] Put some nice formatting on the selected component.
