### ISSUE TITLE
User can sort through user contacts

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/interview-frontend#7]
# Motivation
We want to sort user contacts. This will include sort by name and ID.

# Tasks
- [x] Create a component that lets us select between name and ID.
- [x] Be able to also select ascending or descending order.
- [x] Be get the list sorted correctly based on ID or name.
- [x] Make sure that the correct item is selected on after a sort is done.
- [x] Make sure that the sorted items stay in their state while they are sorted.
